package fr.lip6.move.coloane.extensions.importFromBPEL.importFromBPEL;

/**
 * A BPEL Process Monitor (hand-write)
 * used to make sure what kind of monitors
 * should be generated by the phase Monitor Generation.
 * 
 * author: Jun ZHU (LIP6,UPMC, France & School of Computer Science, NUDT, China)
 * e-mail: mail.zhujun@gmail.com
 * create date: 04-05-2009
 */

public class BPELProcessMonitor {
	
	// Define the Incidence Matrix of Petri Nets
	// in a vector Matrix[][]
	// ** Monitor Generation **
	// It is required to define the incidence matrix 
	// with varibles m and n to define the matrix.
	// ## Monitor Generation ##
	int[][] Matrix = new int[10][15];
	
}
