#!/bin/sh
#proxy
if [ $# -ne 1 ] 
then
 echo "Il faut un parametre : le fichier .jar"
 exit 1
fi
if [ ! -f "$1" ]
then
 echo "Le fichier $1 n'existe pas"
 exit 1
fi
java -jar $1 localhost 8080 132.227.64.27 7001


