package fr.lip6.move.coloane.api.session.controller;

/**
BBBBMMBBMMMMMMMMBBBBBMBBMMMMBBBRXYi:,,,:iVXXVXXWRRRBBRBBBRMBRBBBRRBMMMMMMMMM
BBMMMMBBBMMMMMMMBBBMMMBBMMMMBBRXt:,..:,:tYIIYIVXVYVXVXBRWYWRBRBMMBMMMMMMMMMM
MMMMBMMMMBBBBMMMBBBBBBBMMMMBRXVi:,,.,.,;itiiItIY+iiIIIVXXVXYXRRBMMMMMMMMMMMM
MMMMMMMMBBBMMMMBBBBBBBBBMMBWIt+:,,..,.::++itt+t++i++iItIYXWXXWWBMMMMMMMMMMMM
MMMMMMMMMMMMMBRBBRBBBRBBMMBWi+,,.....,:,;+iI;ti+++:+IYItVWRBBBBBMMMMMMMMMMMM
MMMMMMMMMMBBBBBBRRBBBMBBMMRWX;......,,..+iII++ti;.,tVXVIXRBBBMMMMMMMMMMMMMMM
BMMMMMMMMMBBBBBMBRBRWXWWBMRIYX;......,..+tVIi;I;, ,VVXVYWRBMMMMMMMMMMMMMMMMM
BMMMBMMMBMMBBBBMMBXVXXWBWXI+;IY;,.....,.:iVYtiI:...VVVXIWWBMMMMMMMMMMMMMMMMM
MMMMMMBBBMMMMBMMWYItiiIIII+:,:iY:.....,,,+tXtit:...IVVVIVRBMMMMMMMMMMMMMMMMM
MMMMMMBBMMMMBBBWYii+;+iIXY+:::;t+..  ..,,;:IVti+..,;VVVIYRBBMMMMMMMMMMMMMMMM
RBRRWWWWWWRBBBBRRWRWYiiiYitVI+;;YMMMMMMMBBBBRRRWBBBRRRBMMMMMBRWWWWXVYIIttii+
XWRBBBBBBBBBBBBBRRWWItiiIVXY++;;+VMMRWWRRRBRWWWRMMBRWWWBMMMMMRRWWWWXVYYIttii
XWRRBBBBBBBMBBBBBRX+iIYVWWWXI+;++tXMBRRRRMMMMBRWRBMMMBRRBMMMMMBRWWWXXXVYItii
XWWWWRBBMBMMBBBRBRXYYYIYYYYVYtitIIVRMBBBMMMMMMRRRRBMMMMBRBMMMMMBRWWWXXWVItti
XXVVXWBMMBMMMBBBBBBBRWXVYYItYVVXXWXWBBRRBMMMMBBBBBBRRBMBRBMMMMMMMRRWWWWXYItt
VVVVWWWBBMMMMBMBBBBMMMMBXVYYYYYYIYXRBBBWRRBBRBBBBBRRRRRBRRBMMMMMMMBRRRRWXVYI
IIVYXWWRBMMMMMBBRBMMMMMMMMBVVVYItttWBBRWVVWRBMMMMRRBRRBBBBBBBBMMMBRRRBBRWWXY
IiIYXWXRRBBMBBWVYIIVIIIIYWXi++iittVRBBRWXYYVXBMRRBBBBBBBBRRRWWWRBBBRRRBBRRWX
iitYVVXXRBBMBBXVYYVVItIIIIIIYItitYWRBBBRXVYXXWMRXXWWRWRRRWWWWWWWBBBBBBBBBRRR
itttIXXXRRBBBMBBBRBRWXXVYYIIIYYttIXRBBBRXXXWXRMBXWWWWWXXWWWWWXXXRRBBBBBBBBBR 
 */

public interface IMessage {

}
