[ PT-Net-place/.style
  = { shape=circle
    , draw=black
    , very thick
    , minimum size=.5cm
    }
, PT-Net-transition/.style
  = { shape=rectangle
    , draw=black
    , very thick
    , minimum width=1cm
    , minimum height=.2cm
    }
, PT-Net-arc/.style
  = { -latex
    , very thick
    , draw=black
    }
, PT-Net-marking/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-name/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-valuation/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-authors/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-version/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-title/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-date/.style
  = { shape=rectangle
    , draw=none
    }
, PT-Net-note/.style
  = { shape=rectangle
    , draw=none
    }
]
