name: Java CI with Maven

on: 
 push:
   branches: [ master ]
 repository_dispatch:
   types: [rebuild]

jobs:
  build:
    name: Maven
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK 
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '24'
        cache: 'maven'
    - name: Setup Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9
    - name: Build with Maven
      run: mvn -Djdk.xml.maxGeneralEntitySizeLimit=0 -Djdk.xml.totalEntitySizeLimit=0 -e generate-sources install 
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: update-site/target/repository # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true 
